name: Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v2

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: integration-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            integration-pip-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
          python -m pip install --upgrade poetry
          poetry --version
          poetry install

      - name: Install dependencies
        run: poetry install

      - name: Test integration
        run: ./scripts/test_integration.sh
