---
name: Lint

"on":
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: poetry install

      - name: Lint
        run: ./scripts/lint.sh
